### ISSUE TITLE
Groovy 2.5 breaks plugin contract

### ISSUE THREAD

**Issue by michael-mclawhorn** [crizzis/codenarc-maven-plugin#1]
Groovy-all isn't a jar now but a pom and as a result this plugin fails on groovy later than early 2.5.

**Comment by crizzis** [comment]
Hi @michael-mclawhorn, could you please provide a MRE for the issue? 

The plugin does not depend on a particular Groovy version, as such. In fact, I have recently used it successfully with Groovy 3.0.9. 

You might want to upgrade the CodeNarc version itself, though, to one that fully supports the version of Groovy you want. You can do this using the `plugin > dependencies` section (see the [docs](https://crizzis.github.io/codenarc-maven-plugin/faq.html) for more info on how to customize CodeNarc).

**Comment by crizzis** [comment]
Closing the issue due to inactivity, @michael-mclawhorn if I can be of any further assistance, please let me know.
